apiVersion: apps/v1
kind: Deployment
metadata: 
  name: student
  labels: 
    app: student
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
  template:
    metadata: 
      name: student
      labels:
        app: student
    spec:
      containers:
        - name: http
          image: dmirge/student:latest
          resources: 
            requests:    
              cpu: "25m"
              memory: "50Mi"
            limits:      
              cpu: "50m"
              memory: "100Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  selector:
    matchLabels:
      app: student
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:  
  name: student-hpa1
  labels:
    app: student-hpa1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: student
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student
spec:
  type: ClusterIP  # This exposes the service internally in the cluster
  selector:
    app: student      # It selects the 'todo' app to route traffic to its pods
  ports:
    - protocol: TCP
      port: 80        # The port the service will expose
      targetPort: 80  # The port your container is listening on
